### ISSUE TITLE
Not finding directory when using Cedar.computecanada.ca

### ISSUE THREAD

**Issue by LesterWYoung** [jimmyliu1326/CANS#4]
Hi There,

I've been trying to use CANS on ComputeCanada's Cedar server. I installed cans via conda in my home directory, but haven't had any luck running it in scratch. I tried using both slurm and interactively.  Here's the command and the error message:

` CANS.sh -i samples.csv -o ad135 -e 6000 -d 700 -t 4 -s 1000 --mode dynamic`
`CANS: AD135 directory cannot be found, check its path listed in the input file, exiting
`
I tried with both ad135 and AD135 in the current directory

**Comment by jimmyliu1326** [comment]
Can you verify if the fastq path you provided in `samples.csv` is correct? Note that the path in `samples.csv` should be pointing to a **directory** that contains the fastq files and not pointing to a single fastq file.
